name: Server CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd server && cargo build --verbose
    - name: Check formatting
      run: cd server && rustfmt --check --edition 2018 $(find src/ -name "*.rs")
    - name: Run tests
      run: cd server && cargo test --verbose
