name: Server CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check formatting
      run: rustfmt --check --edition 2018 $(find src/ -name "*.rs")
    - name: Run tests
      run: cargo test --verbose
